### ISSUE TITLE
You can't use app.control.broadcast() without mypy complaining

### ISSUE THREAD

**Issue by colons** [sbdchd/celery-types#28]
The following code leads to a mypy complaint (`broadcast.py:5: error: "Control" has no attribute "broadcast"`):

```python
from celery import Celery

app = Celery()

app.control.broadcast()
```

`broadcast()` is a [real method](https://docs.celeryproject.org/en/stable/userguide/workers.html#the-broadcast-function) of `Control`, which you've [defined](https://github.com/sbdchd/celery-types/blob/main/typings/celery/app/control.pyi) as `...`

it'd be cool if `Control` could be made less strict while these annotations don't exist

**Comment by sbdchd** [comment]
Thanks for the report, should be fixed in version 0.8.0 on pypi

**Comment by colons** [comment]
i'm really confused about this release; [according to pypi](https://pypi.org/project/celery-types/#history), 0.8.0 was released in july

locally, i can see that this change fixes the issue, but the CI server i'm working on (which caches pypi packages and has been seeing 0.8.0 for a while) is still failing with this, and i have no idea how to get it to use the right version

**Comment by sbdchd** [comment]
Oh looking at the git history I think I previously made a release called 0.8.0 in July and never pushed that commit up, so when I created a new release with the same version it was probably a no-op in PyPI.

I've just released a new version: 0.8.1 which hopefully fixes the issue.

**Comment by colons** [comment]
okay yes this sorted it! thank you for this project and for both of the very quick responses
